name: Build Frontend

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Archive build
        run: |
          zip -r frontend-build.zip dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/frontend-build.zip

  backend:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Archive build
        run: |
          zip -r backend.zip *.py requirements.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: backend/backend.zip
